### ISSUE TITLE
Error occurred during training rainbow on Treechop

### ISSUE THREAD

**Issue by yoonjw0** [minerllabs/quick_start#5]
I just run your implementation rainbow script on my machine.
Error occurred during training rainbow on Treechop.

I think there is something wrong during env.step function is 
receiving message communication with malmo
can you help me? error messages are below

 File "/root/miniconda/lib/python3.7/site-packages/minerl/env/core.py", line 527, in step
    reward, done, sent = struct.unpack('!dbb', reply)
TypeError: a bytes-like object is required, not 'NoneType'

execute rainbow.sh
.....
INFO     - 2019-07-22 04:45:35,103 - [chainerrl.experiments.train_agent train_agent 68] statistics:[('average_q', 0.1883753465166074), ('average_loss', 3.5857960946642597), ('n_updates', 8567)]
INFO     - 2019-07-22 04:47:50,474 - [chainerrl.experiments.train_agent train_agent 67] outdir:/shared/storage/personal/jinwoo.yoon/results/MineRLTreechop-v0/rainbow/20190722T040028.790414 step:41278 episode:21 R:0.0
INFO     - 2019-07-22 04:47:50,474 - [chainerrl.experiments.train_agent train_agent 68] statistics:[('average_q', 0.20016808421641685), ('average_loss', 3.4986483235618375), ('n_updates', 9067)]
INFO     - 2019-07-22 04:49:53,632 - [chainerrl.experiments.train_agent train_agent 67] outdir:/shared/storage/personal/jinwoo.yoon/results/MineRLTreechop-v0/rainbow/20190722T040028.790414 step:43278 episode:22 R:4.0
INFO     - 2019-07-22 04:49:53,635 - [chainerrl.experiments.train_agent train_agent 68] statistics:[('average_q', 0.1945552027176348), ('average_loss', 3.4944816582370826), ('n_updates', 9567)]
INFO     - 2019-07-22 04:53:11,385 - [chainerrl.experiments.train_agent save_agent 274] Saved the agent to /shared/storage/personal/jinwoo.yoon/results/MineRLTreechop-v0/rainbow/20190722T040028.790414/44291_except
ERROR    - 2019-07-22 04:53:11,386 - [__main__ main 132] execution failed.

Traceback (most recent call last):
  File "dqn_family.py", line 273, in <module>
    main()
  File "dqn_family.py", line 130, in main
    _main(args)
  File "dqn_family.py", line 265, in _main
    outdir=args.outdir, eval_env=eval_env, save_best_so_far_agent=True,
  File "/root/miniconda/lib/python3.7/site-packages/chainerrl/experiments/train_agent.py", line 163, in train_agent_with_evaluation
    logger=logger)
  File "/root/miniconda/lib/python3.7/site-packages/chainerrl/experiments/train_agent.py", line 54, in train_agent
    obs, r, done, info = env.step(action)
  File "/root/.local/lib/python3.7/site-packages/gym/core.py", line 282, in step
    return self.env.step(self.action(action))
  File "/root/miniconda/lib/python3.7/site-packages/chainerrl/wrappers/atari_wrappers.py", line 210, in step
    ob, reward, done, info = self.env.step(action)
  File "/root/.local/lib/python3.7/site-packages/gym/core.py", line 258, in step
    observation, reward, done, info = self.env.step(action)
  File "/root/.local/lib/python3.7/site-packages/gym/core.py", line 258, in step
    observation, reward, done, info = self.env.step(action)
  File "/root/.local/lib/python3.7/site-packages/gym/core.py", line 258, in step
    observation, reward, done, info = self.env.step(action)
  File "/root/quick_start/chainerrl_baselines/baselines/env_wrappers.py", line 110, in step
    obs, reward, done, info = self.env.step(action)
  File "/root/.local/lib/python3.7/site-packages/gym/core.py", line 224, in step
    return self.env.step(action)
  File "/root/miniconda/lib/python3.7/site-packages/chainerrl/wrappers/continuing_time_limit.py", line 38, in step
    observation, reward, done, info = self.env.step(action)
  File "/root/miniconda/lib/python3.7/site-packages/minerl/env/core.py", line 527, in step
    reward, done, sent = struct.unpack('!dbb', reply)
TypeError: a bytes-like object is required, not 'NoneType'
ERROR    - 2019-07-22 04:53:12,426 - [minerl.env.malmo _kill_minecraft_via_malmoenv 606] Attempted to send kill command to minecraft process and failed.
INFO     - 2019-07-22 04:53:12,427 - [minerl.env.malmo on_terminate 277] Minecraft process psutil.Process(pid=2194, status='terminated') terminated with exit code 0

**Comment by MadcowD** [comment]
Could you upload your ./logs folder?

yoonjw0 <notifications@github.com> schrieb am Mo. 22. Juli 2019 um 03:51:

**Comment by H-rim** [comment]
I'm the one who's working on this project with "Yoonjw0" and I write this reply on behalf of him who's away.
[here](url
[logs.zip](https://github.com/minerllabs/quick_start/files/3420318/logs.zip)
)'s the ./logs folder you asked.
